package com.rtejada.receipt.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Receipt")
public class PageReceipt {

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "UserIdIndex", attributeName = "UserId")
    private String userId;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "UserIdIndex", attributeName = "Path")
    private String path;

    @DynamoDBAttribute(attributeName = "JsonConfig")
    private String jsonConfig;
}
